export const funnelData = [
  {
    step: 1,
    name: "App launch",
    users: 10000,
    color: "#1D9E75",
    status: "Good",
    avgTime: "—",
    why: "Entry point. All users who open the app reach here.",
    fix: "Monitor install-to-open rate. No action needed here.",
  },
  {
    step: 2,
    name: "Email entry",
    users: 8200,
    color: "#1D9E75",
    status: "Good",
    avgTime: "28s avg",
    why: "18% leave before entering email — likely distractions or accidental opens.",
    fix: "Add Google or Apple sign-in to reduce friction at this step.",
  },
  {
    step: 3,
    name: "OTP verify",
    users: 3900,
    color: "#E24B4A",
    status: "Critical",
    avgTime: "94s avg",
    why: "Biggest drop. 52% of users lost here — OTP expires or users switch apps and forget.",
    fix: "Extend OTP to 10 minutes. Add SMS fallback. Show resend button immediately.",
  },
  {
    step: 4,
    name: "Profile setup",
    users: 2450,
    color: "#EF9F27",
    status: "Warning",
    avgTime: "2m 12s avg",
    why: "Too many required fields before users have seen Hushh's value.",
    fix: "Make all fields optional. Defer to post-activation. Add a progress bar.",
  },
  {
    step: 5,
    name: "Activated",
    users: 2100,
    color: "#378ADD",
    status: "Target",
    avgTime: "Goal",
    why: "User completed onboarding and experienced Hushh's core value.",
    fix: "Focus on Day-1 engagement to convert activated users into retained users.",
  },
];

export const recommendations = [
  {
    rank: 1,
    title: "Extend OTP expiry + add SMS fallback",
    detail: "Biggest single fix. Recovering half the OTP drop transforms overall activation.",
    impact: "+18%",
    level: "critical",
  },
  {
    rank: 2,
    title: "Make profile fields optional",
    detail: "Let users experience value first. Collect data post-activation.",
    impact: "+8%",
    level: "warning",
  },
  {
    rank: 3,
    title: "Real-time email validation",
    detail: "Catch typos before OTP is sent. Simple frontend change, high leverage.",
    impact: "+5%",
    level: "warning",
  },
  {
    rank: 4,
    title: "Add step progress indicator",
    detail: "Show users how close they are to finishing. Reduces anxiety-driven exits.",
    impact: "+3%",
    level: "good",
  },
];
